/*
 * License header and template references generated by NetBeans IDE.
 */

/**
 * The AlgorithmCase class represents an ethics case related to algorithms,
 * especially cases involving algorithmic bias.
 * 
 * This class extends the EthicsCase class and adds a specific bias type.
 * 
 * @author fuche
 */
class AlgorithmCase extends EthicsCase {

    // Stores the type of algorithmic bias involved in the case
    private String biasType;

    /**
     * Constructor for creating an AlgorithmCase object.
     * 
     * @param caseTitle   the title of the ethics case
     * @param description the description/details of the case
     * @param biasType    the type of bias involved
     */
    public AlgorithmCase(String caseTitle, String description, String biasType) {
        // Call the parent class constructor
        super(caseTitle, description, "AlgorithmCase");

        // Initialize bias type
        this.biasType = biasType;

        // Create a new Verdict object for this case
        this.verdict = new Verdict();
    }

    /**
     * Returns the bias type of the case.
     * 
     * @return the bias type
     */
    public String getBiasType() {
        return biasType;
    }

    /**
     * Returns a string representation of the AlgorithmCase object.
     * 
     * @return formatted case information including bias type
     */
    @Override
    public String toString() {
        return super.toString() + ", bias type: " + biasType;
    }
}