/*
 * License header and template references generated by NetBeans IDE.
 */

/**
 * The EthicsCase class represents a general ethics case.
 * 
 * It stores basic information about the case, including the title,
 * description, category, and the verdict associated with the case.
 * 
 * @author fuche
 */
public class EthicsCase {

    // Title of the ethics case
    private String caseTitle;

    // Detailed description of the case
    private String description;

    // Category/type of the ethics case
    private String category;

    // Verdict object associated with this case
    public Verdict verdict;

    /**
     * Constructor for creating an EthicsCase object.
     * 
     * @param caseTitle   the title of the case
     * @param description the description/details of the case
     * @param category    the category of the case
     */
    EthicsCase(String caseTitle, String description, String category) {
        this.caseTitle = caseTitle;
        this.description = description;
        this.category = category;

        // Initialize a default verdict object
        this.verdict = new Verdict();
    }

    /**
     * Returns the title of the case.
     * 
     * @return the case title
     */
    public String getCaseTitle() {
        return caseTitle;
    }

    /**
     * Returns the description of the case.
     * 
     * @return the case description
     */
    public String getDescription() {
        return description;
    }

    /**
     * Returns the category of the case.
     * 
     * @return the case category
     */
    public String getCategory() {
        return category;
    }

    /**
     * Returns the verdict associated with this case.
     * 
     * @return the verdict object
     */
    public Verdict getStudentVerdict() {
        return verdict;
    }

    /**
     * Returns a string representation of the EthicsCase object.
     * 
     * @return formatted case information
     */
    @Override
    public String toString() {
        return "Title: " + caseTitle
                + ", description: " + description
                + ", category: " + category;
    }
}
