/*
 * License header and template references generated by NetBeans IDE.
 */

/**
 * The IntellectualPropertyCase class represents an ethics case
 * related to intellectual property issues.
 * 
 * This class extends the EthicsCase class and adds information
 * about the specific type of intellectual property involved.
 * 
 * @author fuche
 */
public class IntellectualPropertyCase extends EthicsCase {

    // Stores the type of intellectual property involved in the case
    private String ipType;

    /**
     * Constructor for creating an IntellectualPropertyCase object.
     * 
     * @param caseTitle   the title of the ethics case
     * @param description the description/details of the case
     * @param ipType      the type of intellectual property involved
     */
    public IntellectualPropertyCase(String caseTitle, String description, String ipType) {

        // Call the parent class constructor with the category
        // "Intellectual Property"
        super(caseTitle, description, "Intellectual Property");

        // Initialize the intellectual property type
        this.ipType = ipType;

        // Create a new Verdict object for this case
        this.verdict = new Verdict();
    }

    /**
     * Returns the intellectual property type of the case.
     * 
     * @return the intellectual property type
     */
    public String getIpType() {
        return ipType;
    }

    /**
     * Returns a string representation of the
     * IntellectualPropertyCase object.
     * 
     * @return formatted case information including IP type
     */
    @Override
    public String toString() {
        return super.toString() + ", ipType: " + ipType;
    }
}